runtime: python312

instance_class: F1

entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 5
  max_instances: 10

env_variables:
  PYTHONUNBUFFERED: "true"